version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/package.json" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    versioning-strategy: "increase"
