version: "3.8"

services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000" # Expose Juice Shop on port 3000
    volumes:
      # Mount the named volume 'js_data' to /juice-shop inside the container
      # This is where Juice Shop store persistent data like user progress or challenges
      - js_data:/juice-shop
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine # Using a lightweight Caddy image
    container_name: caddy
    ports:
      - "80:80" # Expose Caddy on port 80 (HTTP)
      - "443:443" # Expose Caddy on port 443 (HTTPS)
    volumes:
      # Mount the named volume 'caddy_data' for Caddy's persistent data (e.g., certificates)
      - caddy_data:/data
      # Mount your Caddyfile to configure Caddy
      - ${DATA_FOLDER}/caddy/Caddyfile # Setting from .env file
    restart: unless-stopped
    depends_on:
      - juice-shop # Ensure Juice Shop starts before Caddy

volumes:
  js_data:
    external: true # Indicates that this volume is pre-created
  caddy_data:
    external: true # Indicates that this volume is pre-created
