version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # Root level
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/frontend"  # Frontend folder
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 5
