name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}

env:
  SEMGREP_SARIF_FILE: 'results.sarif'

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-24.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci --supply-chain --sarif-output '${{ env.SEMGREP_SARIF_FILE }}'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: '${{ env.SEMGREP_SARIF_FILE }}'
          category: semgrep-sca
