name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}

env:
  SEMGREP_SARIF_FILE: 'results.sarif'
  SEMGREP_ARTIFACT_NAME: 'semgrep-sarif'

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-24.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci --supply-chain --sarif-output results.sarif
      - name: Upload Dependency Sarif output
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SEMGREP_ARTIFACT_NAME }}
          path: ${{ env.SEMGREP_SARIF_FILE }}

  upload-results:
    name: upload-sarif
    needs: ['semgrep']
    if: ${{ always() }}
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    steps:
    - name: Download semgrep sarif artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.SEMGREP_ARTIFACT_NAME }}
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ env.SEMGREP_SARIF_FILE }}
        category: semgrep
    
